### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by Bogalusa1** [rrirower/DP2SceneGraphWizard#46]
hello
after use alpha 8
am getting
<img width="1091" alt="Captura de Tela 2023-10-21 às 13 13 58" src="https://github.com/rrirower/DP2SceneGraphWizard/assets/148657891/9c9949c0-774a-46ac-a9aa-8970a41bac79">
 error, it does not load the feed url

**Comment by rrirower** [comment]
Can you be more specific? Are you receiving an error message? Can you take a screen image of the error?

I'll need your feed URL to debug further.

**Comment by rrirower** [comment]
Are you still dealing with this issue?

**Comment by ferdiworks** [comment]
@Bogalusa1 Sounds like Roku devices don't like your encoder settings or network stability. Test your Internet connection: https://testmy.net/upload Next: Check your live streaming Bitrate to be within 3400 to 4000. If you are live streaming to more than one location at the same time use a separate RTMP and Key for OTT Roku because if the livesdtream is shared and bottlenecking packages Roku may not accept it!

**Comment by ferdiworks** [comment]
@Bogalusa1 Question where is the feed hosted? Is this being used from a WordPress plugin? The feed URL does not end in a .json. I worked with clients who used WP smart tv and had a similar issue. What worked was to use a redirect plugin and redirect it to a new URL with the .json extension. an example would be to install a redirect plugin and point it to your feed but use the .json link https://api.npoint.io/75f39fbf908ff08ba323.json

**Comment by rrirower** [comment]
@Bogalusa1 ferdiworks is correct.  Your feed file will not be parsed if it is missing the appropriate extension (.xml or .json).  The code needs to know what type of feed file you are using.

**Comment by rrirower** [comment]
@Bogalusa1 Have you resolved this?

**Comment by rrirower** [comment]
No response from the user. Closed.
